"""
Earth Geography Module.

Provides real-world terrain classification from latitude/longitude coordinates
using:
- Natural Earth 110m land polygons (rasterized to 0.25° land mask via Shapely)
- Köppen-Geiger inspired climate/biome model for terrain classification
- Latitude-based temperature zones for fertility estimation

Data source: Natural Earth (naturalearthdata.com), public domain.
Land mask generated by generate_landmask.py using Shapely point-in-polygon.
"""

import numpy as np
import os
from typing import Optional


# ============================================================================
# Load pre-computed land mask (generated from Natural Earth 110m polygons)
# ============================================================================

_DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
_LANDMASK_PATH = os.path.join(_DATA_DIR, "landmask.npy")

# Grid parameters matching generate_landmask.py
_MASK_RESOLUTION = 0.25  # degrees per cell
_MASK_LAT_MIN, _MASK_LAT_MAX = -90.0, 90.0
_MASK_LNG_MIN, _MASK_LNG_MAX = -180.0, 180.0

# Load land mask (720 x 1440 boolean grid at 0.25° resolution)
if os.path.exists(_LANDMASK_PATH):
    _LAND_MASK = np.load(_LANDMASK_PATH)
    _MASK_ROWS, _MASK_COLS = _LAND_MASK.shape
else:
    _LAND_MASK = None
    _MASK_ROWS, _MASK_COLS = 720, 1440

# ============================================================================
# Load pre-computed Earth system grids (0.5° resolution, from generate_earth_data.py)
# ============================================================================

_EARTH_RESOLUTION = 0.5  # degrees per cell for earth system grids
_EARTH_GRIDS = {}

for _grid_name in ["terrain", "biome", "elevation", "temperature", "precipitation",
                    "fertility", "minerals", "freshwater", "fossil_fuels"]:
    _path = os.path.join(_DATA_DIR, f"earth_{_grid_name}.npy")
    if os.path.exists(_path):
        _EARTH_GRIDS[_grid_name] = np.load(_path)

_HAS_EARTH_DATA = "terrain" in _EARTH_GRIDS


# ============================================================================
# Terrain Types (same IDs as before)
# ============================================================================

class TerrainType:
    OCEAN = 0
    PLAINS = 1
    FOREST = 2
    MOUNTAINS = 3
    DESERT = 4
    TUNDRA = 5

    NAMES = {0: "Ocean", 1: "Plains", 2: "Forest", 3: "Mountains",
             4: "Desert", 5: "Tundra"}


# ============================================================================
# Simplified Land/Ocean Detection
# ============================================================================

# Embedded simplified continental bounding boxes (lat_min, lat_max, lng_min, lng_max)
# These are rough polygonal approximations - enough for gameplay, not cartography
CONTINENTAL_REGIONS = [
    # Africa
    {"name": "Africa", "bounds": [(-35, 37, -18, 52)],
     "detail": [(-35, -22, 16, 33), (-22, 0, 8, 42), (0, 15, -18, 42),
                (15, 37, -18, 35), (5, 12, -18, -5)]},
    # Europe
    {"name": "Europe", "bounds": [(35, 71, -10, 40)],
     "detail": [(35, 45, -10, 30), (45, 55, -5, 40), (55, 65, 5, 35),
                (65, 71, 10, 32), (36, 42, -10, 3)]},
    # Asia
    {"name": "Asia", "bounds": [(1, 77, 25, 180)],
     "detail": [(50, 77, 60, 180), (35, 55, 25, 140), (1, 35, 65, 145),
                (25, 42, 25, 65), (8, 25, 68, 90), (1, 8, 95, 108)]},
    # North America
    {"name": "North America", "bounds": [(15, 72, -170, -50)],
     "detail": [(15, 30, -120, -75), (30, 50, -130, -60), (50, 60, -140, -55),
                (60, 72, -170, -60), (15, 22, -105, -85)]},
    # South America
    {"name": "South America", "bounds": [(-56, 13, -82, -34)],
     "detail": [(-56, -40, -76, -62), (-40, -20, -72, -40), (-20, 0, -82, -34),
                (0, 13, -80, -50)]},
    # Australia / Oceania
    {"name": "Australia", "bounds": [(-45, -10, 112, 155)],
     "detail": [(-40, -10, 112, 155), (-47, -40, 166, 179)]},
    # Major Islands
    {"name": "Greenland", "bounds": [(60, 84, -73, -12)],
     "detail": [(60, 84, -73, -12)]},
    {"name": "Indonesia", "bounds": [(-8, 6, 95, 141)],
     "detail": [(-8, 6, 95, 141)]},
    {"name": "Japan", "bounds": [(30, 46, 128, 146)],
     "detail": [(30, 46, 128, 146)]},
    {"name": "UK", "bounds": [(50, 59, -8, 2)],
     "detail": [(50, 59, -8, 2)]},
    {"name": "Madagascar", "bounds": [(-26, -12, 43, 51)],
     "detail": [(-26, -12, 43, 51)]},
    {"name": "New Zealand", "bounds": [(-47, -34, 166, 179)],
     "detail": [(-47, -34, 166, 179)]},
    {"name": "Philippines", "bounds": [(5, 20, 117, 127)],
     "detail": [(5, 20, 117, 127)]},
    {"name": "Sri Lanka", "bounds": [(6, 10, 79, 82)],
     "detail": [(6, 10, 79, 82)]},
    {"name": "Iceland", "bounds": [(63, 66, -24, -13)],
     "detail": [(63, 66, -24, -13)]},
    {"name": "India", "bounds": [(8, 35, 68, 90)],
     "detail": [(8, 35, 68, 90)]},
    {"name": "Arabian Peninsula", "bounds": [(12, 32, 34, 60)],
     "detail": [(12, 32, 34, 60)]},
]


def is_land(lat: float, lng: float) -> bool:
    """
    Check if a coordinate is land using the pre-computed raster mask
    derived from Natural Earth 110m land polygons.

    Falls back to bounding-box heuristic if mask not available.
    """
    if _LAND_MASK is not None:
        r = int((_MASK_LAT_MAX - lat) / _MASK_RESOLUTION)
        c = int((lng - _MASK_LNG_MIN) / _MASK_RESOLUTION)
        r = max(0, min(r, _MASK_ROWS - 1))
        c = max(0, min(c, _MASK_COLS - 1))
        return bool(_LAND_MASK[r, c])

    # Fallback: bounding-box heuristic
    return _is_land_bbox(lat, lng)


def is_land_array(lats: np.ndarray, lngs: np.ndarray) -> np.ndarray:
    """Vectorized land check for arrays of coordinates."""
    if _LAND_MASK is not None:
        rows = np.clip(
            ((_MASK_LAT_MAX - lats) / _MASK_RESOLUTION).astype(int),
            0, _MASK_ROWS - 1
        )
        cols = np.clip(
            ((lngs - _MASK_LNG_MIN) / _MASK_RESOLUTION).astype(int),
            0, _MASK_COLS - 1
        )
        return _LAND_MASK[rows, cols]

    # Fallback
    return np.array([_is_land_bbox(lat, lng) for lat, lng in zip(lats, lngs)])


def _is_land_bbox(lat: float, lng: float) -> bool:
    """Fallback bounding-box land detection (used if mask not available)."""
    for region in CONTINENTAL_REGIONS:
        for box in region["detail"]:
            lat_min, lat_max, lng_min, lng_max = box
            if lat_min <= lat <= lat_max and lng_min <= lng <= lng_max:
                return True
    return False


# ============================================================================
# Biome/Terrain Classification from Coordinates
# ============================================================================

def _lookup_earth_grid(grid_name: str, lat: float, lng: float, default=0):
    """Look up a value from a pre-computed 0.5° Earth system grid."""
    grid = _EARTH_GRIDS.get(grid_name)
    if grid is None:
        return default
    rows, cols = grid.shape
    r = int(np.clip((90.0 - lat) / _EARTH_RESOLUTION, 0, rows - 1))
    c = int(np.clip((lng + 180.0) / _EARTH_RESOLUTION, 0, cols - 1))
    return float(grid[r, c])


def classify_terrain(lat: float, lng: float, seed: int = 42) -> int:
    """
    Classify terrain type from pre-computed Earth system grids.
    Uses Whittaker biome diagram applied to real temperature/precipitation data.
    Falls back to algorithmic model if grids not available.
    """
    if not is_land(lat, lng):
        return TerrainType.OCEAN

    # Use pre-computed terrain grid if available
    if _HAS_EARTH_DATA:
        return int(_lookup_earth_grid("terrain", lat, lng, TerrainType.PLAINS))

    abs_lat = abs(lat)

    # Pseudo-random local variation from coordinates
    # Creates consistent terrain that looks natural
    noise = _terrain_noise(lat, lng, seed)
    mountain_noise = _terrain_noise(lat * 3, lng * 3, seed + 1)

    # Mountains (elevation-based, along known mountain ranges)
    if mountain_noise > 0.7 and _is_mountain_region(lat, lng):
        return TerrainType.MOUNTAINS

    # Tundra: high latitudes
    if abs_lat > 65:
        return TerrainType.TUNDRA

    # Desert: subtropical dry zones (20-35°) and known desert regions
    if _is_desert_region(lat, lng, noise):
        return TerrainType.DESERT

    # Forest: mid-latitudes with enough moisture, tropics
    if _is_forest_region(lat, lng, noise):
        return TerrainType.FOREST

    # Default: Plains/Grassland
    return TerrainType.PLAINS


def _terrain_noise(lat: float, lng: float, seed: int) -> float:
    """Deterministic noise from coordinates (hash-based)."""
    # Simple but effective pseudo-noise
    x = lat * 7.3 + seed * 13.7
    y = lng * 11.1 + seed * 17.3
    n = np.sin(x) * np.cos(y) * np.sin(x * 0.3 + y * 0.7) + \
        np.sin(x * 2.1 + 3.7) * np.cos(y * 1.3 + 2.1) * 0.5
    return (n + 1.5) / 3.0  # Normalize to roughly 0-1


def _is_mountain_region(lat: float, lng: float) -> bool:
    """Check if near known mountain ranges."""
    ranges = [
        # Himalayas / Central Asia
        (25, 45, 65, 105),
        # Alps
        (44, 48, 5, 17),
        # Andes
        (-55, 10, -80, -65),
        # Rocky Mountains
        (30, 60, -125, -105),
        # East African Rift
        (-10, 15, 28, 40),
        # Ural
        (48, 68, 55, 62),
        # Scandinavian
        (58, 70, 5, 15),
        # Atlas
        (30, 37, -5, 10),
    ]
    for lat_min, lat_max, lng_min, lng_max in ranges:
        if lat_min <= lat <= lat_max and lng_min <= lng <= lng_max:
            return True
    return False


def _is_desert_region(lat: float, lng: float, noise: float) -> bool:
    """Check if in a desert zone."""
    abs_lat = abs(lat)

    # Known desert regions
    deserts = [
        # Sahara
        (15, 35, -15, 35),
        # Arabian
        (15, 32, 35, 55),
        # Gobi
        (38, 48, 90, 115),
        # Australian Outback
        (-30, -18, 120, 148),
        # Kalahari / Namib
        (-28, -18, 15, 28),
        # Sonoran / Chihuahuan
        (22, 35, -115, -100),
        # Patagonian
        (-50, -38, -72, -65),
        # Thar
        (23, 30, 68, 75),
        # Karakum / Kyzylkum
        (35, 45, 52, 68),
    ]
    for lat_min, lat_max, lng_min, lng_max in deserts:
        if lat_min <= lat <= lat_max and lng_min <= lng <= lng_max:
            return True

    # General subtropical dry belt
    if 20 < abs_lat < 35 and noise < 0.35:
        return True

    return False


def _is_forest_region(lat: float, lng: float, noise: float) -> bool:
    """Check if in a forested zone."""
    abs_lat = abs(lat)

    # Tropical rainforest belt
    if abs_lat < 15 and noise > 0.3:
        return True

    # Boreal / Taiga forest
    if 50 < abs_lat < 65 and noise > 0.35:
        return True

    # Temperate forest
    if 30 < abs_lat < 55 and noise > 0.5:
        return True

    # Known dense forest regions
    forests = [
        # Amazon
        (-15, 5, -75, -45),
        # Congo
        (-5, 5, 15, 30),
        # Siberian Taiga
        (50, 65, 60, 150),
        # Canadian Boreal
        (48, 60, -140, -60),
        # Southeast Asian
        (0, 20, 95, 130),
    ]
    for lat_min, lat_max, lng_min, lng_max in forests:
        if lat_min <= lat <= lat_max and lng_min <= lng <= lng_max:
            return True

    return False


def get_earth_data(lat: float, lng: float) -> dict:
    """Get all Earth system data for a coordinate."""
    return {
        "terrain": int(_lookup_earth_grid("terrain", lat, lng, 0)),
        "biome": int(_lookup_earth_grid("biome", lat, lng, 0)),
        "elevation": _lookup_earth_grid("elevation", lat, lng, 0.1),
        "temperature": _lookup_earth_grid("temperature", lat, lng, 15.0),
        "precipitation": _lookup_earth_grid("precipitation", lat, lng, 500),
        "fertility": _lookup_earth_grid("fertility", lat, lng, 0.3),
        "minerals": _lookup_earth_grid("minerals", lat, lng, 0.1),
        "freshwater": _lookup_earth_grid("freshwater", lat, lng, 0.3),
        "fossil_fuels": _lookup_earth_grid("fossil_fuels", lat, lng, 0.0),
    }


def get_fertility(lat: float, lng: float, terrain: int) -> float:
    """Estimate soil fertility from pre-computed grid or algorithmic model."""
    if terrain == TerrainType.OCEAN:
        return 0.0

    # Use pre-computed fertility if available
    if _HAS_EARTH_DATA:
        return _lookup_earth_grid("fertility", lat, lng, 0.3)

    abs_lat = abs(lat)
    base = 0.5

    # Tropical = high fertility
    if abs_lat < 20:
        base = 0.8
    # Temperate = good
    elif abs_lat < 45:
        base = 0.65
    # Subarctic = low
    elif abs_lat < 60:
        base = 0.35
    # Arctic = very low
    else:
        base = 0.15

    # Terrain modifiers
    modifiers = {
        TerrainType.PLAINS: 1.0,
        TerrainType.FOREST: 0.9,
        TerrainType.MOUNTAINS: 0.3,
        TerrainType.DESERT: 0.1,
        TerrainType.TUNDRA: 0.15,
    }
    base *= modifiers.get(terrain, 0.5)

    # Add some local variation
    noise = _terrain_noise(lat * 5, lng * 5, 99)
    base *= (0.7 + 0.6 * noise)

    return float(np.clip(base, 0.0, 1.0))


# ============================================================================
# Grid Generation for World Simulation
# ============================================================================

def generate_earth_grid(lat_min: float = -60, lat_max: float = 75,
                        lng_min: float = -180, lng_max: float = 180,
                        cell_size_deg: float = 2.0,
                        seed: int = 42) -> dict:
    """
    Generate terrain, fertility, and resource grids for the simulation.

    Uses pre-computed Earth system data (from generate_earth_data.py) when
    available, falling back to algorithmic models otherwise.
    """
    lats = np.arange(lat_max, lat_min, -cell_size_deg)
    lngs = np.arange(lng_min, lng_max, cell_size_deg)
    rows = len(lats)
    cols = len(lngs)

    terrain = np.zeros((rows, cols), dtype=int)
    fertility = np.zeros((rows, cols))
    elevation = np.zeros((rows, cols))
    minerals = np.zeros((rows, cols))
    freshwater = np.zeros((rows, cols))
    fossil_fuels = np.zeros((rows, cols))

    for r in range(rows):
        for c in range(cols):
            lat, lng = lats[r], lngs[c]

            if _HAS_EARTH_DATA:
                # Use pre-computed Earth system data
                terrain[r, c] = int(_lookup_earth_grid("terrain", lat, lng, 0))
                fertility[r, c] = _lookup_earth_grid("fertility", lat, lng, 0.3)
                elevation[r, c] = _lookup_earth_grid("elevation", lat, lng, 0.1)
                minerals[r, c] = _lookup_earth_grid("minerals", lat, lng, 0.1)
                freshwater[r, c] = _lookup_earth_grid("freshwater", lat, lng, 0.3)
                fossil_fuels[r, c] = _lookup_earth_grid("fossil_fuels", lat, lng, 0.0)
            else:
                t = classify_terrain(lat, lng, seed)
                terrain[r, c] = t
                fertility[r, c] = get_fertility(lat, lng, t)
                elevation[r, c] = 0.2 if t != TerrainType.OCEAN else 0.0

    return {
        "terrain": terrain,
        "fertility": fertility,
        "elevation": elevation,
        "minerals": minerals,
        "freshwater": freshwater,
        "fossil_fuels": fossil_fuels,
        "lats": lats,
        "lngs": lngs,
        "rows": rows,
        "cols": cols,
        "cell_size_deg": cell_size_deg,
        "lat_min": lat_min,
        "lat_max": lat_max,
        "lng_min": lng_min,
        "lng_max": lng_max,
    }


def find_land_spawn_points(n: int, seed: int = 42,
                           prefer_habitable: bool = True) -> list[tuple[float, float]]:
    """Find n random land coordinates for spawning agents."""
    rng = np.random.RandomState(seed)
    points = []
    attempts = 0
    max_attempts = n * 100

    while len(points) < n and attempts < max_attempts:
        lat = rng.uniform(-55, 65)
        lng = rng.uniform(-170, 170)
        attempts += 1

        if is_land(lat, lng):
            if prefer_habitable:
                t = classify_terrain(lat, lng, seed)
                if t in (TerrainType.OCEAN, TerrainType.TUNDRA):
                    continue
                # Prefer non-desert with some probability
                if t == TerrainType.DESERT and rng.random() > 0.3:
                    continue
            points.append((lat, lng))

    return points
